name: Automatic Approve

permissions: {}

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  automatic_approve:
    env: 
      working-directory: ./Software/
    runs-on: ubuntu-latest

    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: mheap/automatic-approve-action@v1
      with:
        token: ${{ secrets.QMK_BOT_TOKEN }}
        workflows: "format.yml,lint.yml,unit_test.yml"
        dangerous_files: "lib/python/,Makefile,paths.mk,builddefs/"
